[toolchain]
moc = "1.9.0"
lintoko = "0.10.0"

[dependencies]
core = "2.5.0"
sha2 = "0.2.1"

[moc]
args = [ "--default-persistent-actors", "-W=M0223,M0236,M0237" ]

[canisters.launcher_backend]
main = "src/backend/main.mo"
candid = "src/backend/launcher_backend.did"

[canisters.launcher_factory]
main = "src/factory/main.mo"
candid = "src/factory/launcher_factory.did"

[canisters.app_template]
main = "src/app_template/main.mo"
candid = "src/app_template/app_template.did"

[build]
outputDir = ".mops/.build"
args = [ "--release" ]
